__BASE__: [
  './coco.yaml',
]

epochs: 270
per_batch_size: 8 # 8 * 8 = 64
anchors: [[[116,90], [156,198], [373,326]], [[30,61], [62,45], [59,119]], [[10,13], [16,30], [33,23]]]

optimizer:
  optimizer: momentum
  lr_init: 0.001  # initial learning rate (SGD=1E-2, Adam=1E-3)
  gamma: 0.1
  milestones: [216, 243]
  gp_weight_decay: 0.0005  # optimizer weight decay 5e-4
  momentum: 0.9  # SGD momentum/Adam beta1
  nesterov: True # update gradients with NAG(Nesterov Accelerated Gradient) algorithm
  loss_scale: 1.0 # loss scale for optimizer
  warmup_epochs: 0  # warmup epochs (fractions ok)
  warmup_momentum: 0.9  # warmup initial momentum
  min_warmup_step: 4000 # minimum warmup step
  group_param: yolov3 # group param strategy

loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false

data:
  num_parallel_workers: 4

  train_transforms:
    - { func_name: mixup, alpha: 1.5, beta: 1.5 }
    - { func_name: random_distort }
    - { func_name: random_expand, fill_value: [123.675, 116.28, 103.53]}
    - { func_name: random_crop }
    - { func_name: fliplr, prob: 0.5 }

  test_transforms:
    - { func_name: resize, target_size: [608, 608] }
    - { func_name: normalize_image, mean: [0.406, 0.456, 0.485], std: [0.225, 0.224, 0.229] }
    - { func_name: image_transpose, bgr2rgb: True, hwc2chw: True }
